spring:
  application:
    name: todo-insight

  # Active profile
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Global Max Pull Request Size
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 20

  # Thymeleaf configuration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

# Application UI Configuration
app:
  ui:
    app-name: Todo Insight
    version: 1.0.0
    api-base: /api
    date-format: MMM dd, yyyy
    date-time-format: MMM dd, yyyy HH:mm
